/**
 * Migration script from v053 to v054
 *
 * Important:
 * - This migration is intentionally self-contained.
 * - Do not import runtime TTS mappings here because migration behavior must stay immutable.
 */

const MIGRATION_V054_FALLBACK_VOICE = "en-US-GuyNeural"

const MIGRATION_V054_KNOWN_EDGE_TTS_VOICES = new Set<string>([
  "af-ZA-AdriNeural",
  "am-ET-AmehaNeural",
  "ar-SA-HamedNeural",
  "as-IN-BiswajitNeural",
  "az-AZ-BabekNeural",
  "be-BY-YauheniNeural",
  "bg-BG-BorislavNeural",
  "bn-BD-NabanitaNeural",
  "bs-BA-GoranNeural",
  "ca-ES-EnricNeural",
  "cs-CZ-AntoninNeural",
  "cy-GB-AledNeural",
  "da-DK-JeppeNeural",
  "de-DE-ConradNeural",
  "el-GR-NestorasNeural",
  "en-GB-RyanNeural",
  "en-NZ-MitchellNeural",
  "en-US-AriaNeural",
  "en-US-DavisNeural",
  "en-US-GuyNeural",
  "en-US-JennyNeural",
  "en-US-MichelleNeural",
  "en-US-TonyNeural",
  "es-ES-AlvaroNeural",
  "et-EE-KertNeural",
  "eu-ES-AnderNeural",
  "fa-IR-FaridNeural",
  "ff-Latn-SN-SambaNeural",
  "fi-FI-HarriNeural",
  "fil-PH-AngeloNeural",
  "fo-FO-PoulNeural",
  "fr-FR-HenriNeural",
  "ga-IE-ColmNeural",
  "gl-ES-RoiNeural",
  "gu-IN-NiranjanNeural",
  "ha-NG-AbubakarNeural",
  "he-IL-AvriNeural",
  "hi-IN-MadhurNeural",
  "hr-HR-SreckoNeural",
  "hu-HU-TamasNeural",
  "hy-AM-HaykNeural",
  "id-ID-ArdiNeural",
  "ig-NG-EzinneNeural",
  "is-IS-GunnarNeural",
  "it-IT-DiegoNeural",
  "ja-JP-KeitaNeural",
  "ja-JP-NanamiNeural",
  "jv-ID-DimasNeural",
  "ka-GE-GiorgiNeural",
  "kk-KZ-DauletNeural",
  "km-KH-PisethNeural",
  "kn-IN-GaganNeural",
  "ko-KR-InJoonNeural",
  "ko-KR-SunHiNeural",
  "ln-CD-BaudouinNeural",
  "lo-LA-ChanthavongNeural",
  "lt-LT-LeonasNeural",
  "lv-LV-NilsNeural",
  "mk-MK-AleksandarNeural",
  "ml-IN-MidhunNeural",
  "mn-MN-BataaNeural",
  "mr-IN-ManoharNeural",
  "ms-MY-OsmanNeural",
  "mt-MT-JosephNeural",
  "my-MM-ThihaNeural",
  "nb-NO-FinnNeural",
  "ne-NP-SagarNeural",
  "nl-NL-MaartenNeural",
  "nn-NO-FinnNeural",
  "or-IN-DineshNeural",
  "pa-IN-OjasNeural",
  "pl-PL-MarekNeural",
  "pt-BR-AntonioNeural",
  "ro-RO-EmilNeural",
  "ru-RU-DmitryNeural",
  "rw-RW-JeanNeural",
  "sd-PK-SalmanNeural",
  "si-LK-SameeraNeural",
  "sk-SK-LukasNeural",
  "sl-SI-RokNeural",
  "so-SO-MuuseNeural",
  "sq-AL-IlirNeural",
  "sr-RS-NicholasNeural",
  "su-ID-JajangNeural",
  "sv-SE-MattiasNeural",
  "sw-KE-RafikiNeural",
  "ta-IN-ValluvarNeural",
  "te-IN-MohanNeural",
  "tg-TJ-SharifNeural",
  "th-TH-NiwatNeural",
  "tk-TM-AmanNeural",
  "tr-TR-AhmetNeural",
  "tt-RU-AidarNeural",
  "ug-CN-KashgarNeural",
  "uk-UA-OstapNeural",
  "ur-PK-AsadNeural",
  "uz-UZ-SardorNeural",
  "vi-VN-NamMinhNeural",
  "xh-ZA-ThembaNeural",
  "yo-NG-AbeoNeural",
  "zh-CN-XiaochenNeural",
  "zh-CN-XiaohanNeural",
  "zh-CN-XiaomengNeural",
  "zh-CN-XiaomoNeural",
  "zh-CN-XiaoqiuNeural",
  "zh-CN-XiaoruiNeural",
  "zh-CN-XiaoshuangNeural",
  "zh-CN-XiaoxiaoNeural",
  "zh-CN-XiaoxuanNeural",
  "zh-CN-XiaoyanNeural",
  "zh-CN-XiaoyiNeural",
  "zh-CN-XiaoyouNeural",
  "zh-CN-XiaozhenNeural",
  "zh-CN-YunfengNeural",
  "zh-CN-YunhaoNeural",
  "zh-CN-YunjianNeural",
  "zh-CN-YunxiaNeural",
  "zh-CN-YunxiNeural",
  "zh-CN-YunyangNeural",
  "zh-CN-YunyeNeural",
  "zh-CN-YunzeNeural",
  "zh-TW-YunJheNeural",
  "zu-ZA-ThembaNeural",
])

const MIGRATION_V054_DEFAULT_LANGUAGE_VOICES: Record<string, string> = {
  "eng": "en-US-GuyNeural",
  "cmn": "zh-CN-YunxiNeural",
  "cmn-Hant": "zh-TW-YunJheNeural",
  "yue": "zh-CN-YunxiNeural",
  "spa": "es-ES-AlvaroNeural",
  "rus": "ru-RU-DmitryNeural",
  "arb": "ar-SA-HamedNeural",
  "ben": "bn-BD-NabanitaNeural",
  "hin": "hi-IN-MadhurNeural",
  "por": "pt-BR-AntonioNeural",
  "ind": "id-ID-ArdiNeural",
  "jpn": "ja-JP-KeitaNeural",
  "fra": "fr-FR-HenriNeural",
  "deu": "de-DE-ConradNeural",
  "jav": "jv-ID-DimasNeural",
  "kor": "ko-KR-InJoonNeural",
  "tel": "te-IN-MohanNeural",
  "vie": "vi-VN-NamMinhNeural",
  "mar": "mr-IN-ManoharNeural",
  "ita": "it-IT-DiegoNeural",
  "tam": "ta-IN-ValluvarNeural",
  "tur": "tr-TR-AhmetNeural",
  "urd": "ur-PK-AsadNeural",
  "guj": "gu-IN-NiranjanNeural",
  "pol": "pl-PL-MarekNeural",
  "ukr": "uk-UA-OstapNeural",
  "kan": "kn-IN-GaganNeural",
  "mai": "en-US-GuyNeural",
  "mal": "ml-IN-MidhunNeural",
  "pes": "fa-IR-FaridNeural",
  "mya": "my-MM-ThihaNeural",
  "swh": "sw-KE-RafikiNeural",
  "sun": "su-ID-JajangNeural",
  "ron": "ro-RO-EmilNeural",
  "pan": "pa-IN-OjasNeural",
  "bho": "en-US-GuyNeural",
  "amh": "am-ET-AmehaNeural",
  "hau": "ha-NG-AbubakarNeural",
  "fuv": "ff-Latn-SN-SambaNeural",
  "bos": "bs-BA-GoranNeural",
  "hrv": "hr-HR-SreckoNeural",
  "nld": "nl-NL-MaartenNeural",
  "srp": "sr-RS-NicholasNeural",
  "tha": "th-TH-NiwatNeural",
  "ckb": "en-US-GuyNeural",
  "yor": "yo-NG-AbeoNeural",
  "uzn": "uz-UZ-SardorNeural",
  "zlm": "ms-MY-OsmanNeural",
  "ibo": "ig-NG-EzinneNeural",
  "npi": "ne-NP-SagarNeural",
  "ceb": "en-US-GuyNeural",
  "skr": "en-US-GuyNeural",
  "tgl": "fil-PH-AngeloNeural",
  "hun": "hu-HU-TamasNeural",
  "azj": "az-AZ-BabekNeural",
  "sin": "si-LK-SameeraNeural",
  "koi": "en-US-GuyNeural",
  "ell": "el-GR-NestorasNeural",
  "ces": "cs-CZ-AntoninNeural",
  "mag": "en-US-GuyNeural",
  "run": "en-US-GuyNeural",
  "bel": "be-BY-YauheniNeural",
  "plt": "en-US-GuyNeural",
  "qug": "en-US-GuyNeural",
  "mad": "en-US-GuyNeural",
  "nya": "en-US-GuyNeural",
  "zyb": "en-US-GuyNeural",
  "pbu": "en-US-GuyNeural",
  "kin": "rw-RW-JeanNeural",
  "zul": "zu-ZA-ThembaNeural",
  "bul": "bg-BG-BorislavNeural",
  "swe": "sv-SE-MattiasNeural",
  "lin": "ln-CD-BaudouinNeural",
  "som": "so-SO-MuuseNeural",
  "hms": "en-US-GuyNeural",
  "hnj": "en-US-GuyNeural",
  "ilo": "en-US-GuyNeural",
  "kaz": "kk-KZ-DauletNeural",
  "heb": "he-IL-AvriNeural",
  "nob": "nb-NO-FinnNeural",
  "nno": "nn-NO-FinnNeural",
  "afr": "af-ZA-AdriNeural",
  "sqi": "sq-AL-IlirNeural",
  "asm": "as-IN-BiswajitNeural",
  "eus": "eu-ES-AnderNeural",
  "bre": "fr-FR-HenriNeural",
  "cat": "ca-ES-EnricNeural",
  "cos": "fr-FR-HenriNeural",
  "cym": "cy-GB-AledNeural",
  "dan": "da-DK-JeppeNeural",
  "div": "si-LK-SameeraNeural",
  "epo": "en-US-GuyNeural",
  "ekk": "et-EE-KertNeural",
  "fao": "fo-FO-PoulNeural",
  "fij": "en-US-GuyNeural",
  "fin": "fi-FI-HarriNeural",
  "fry": "nl-NL-MaartenNeural",
  "gla": "en-GB-RyanNeural",
  "gle": "ga-IE-ColmNeural",
  "glg": "gl-ES-RoiNeural",
  "grn": "es-ES-AlvaroNeural",
  "hat": "fr-FR-HenriNeural",
  "haw": "en-US-GuyNeural",
  "hye": "hy-AM-HaykNeural",
  "ido": "en-US-GuyNeural",
  "ina": "en-US-GuyNeural",
  "isl": "is-IS-GunnarNeural",
  "kat": "ka-GE-GiorgiNeural",
  "khm": "km-KH-PisethNeural",
  "kir": "kk-KZ-DauletNeural",
  "lao": "lo-LA-ChanthavongNeural",
  "lat": "it-IT-DiegoNeural",
  "lvs": "lv-LV-NilsNeural",
  "lit": "lt-LT-LeonasNeural",
  "ltz": "fr-FR-HenriNeural",
  "mkd": "mk-MK-AleksandarNeural",
  "mlt": "mt-MT-JosephNeural",
  "mon": "mn-MN-BataaNeural",
  "mri": "en-NZ-MitchellNeural",
  "nso": "en-US-GuyNeural",
  "oci": "fr-FR-HenriNeural",
  "ori": "or-IN-DineshNeural",
  "orm": "en-US-GuyNeural",
  "prs": "en-US-GuyNeural",
  "san": "hi-IN-MadhurNeural",
  "slk": "sk-SK-LukasNeural",
  "slv": "sl-SI-RokNeural",
  "smo": "en-US-GuyNeural",
  "sna": "en-US-GuyNeural",
  "snd": "sd-PK-SalmanNeural",
  "sot": "en-US-GuyNeural",
  "tah": "fr-FR-HenriNeural",
  "tat": "tt-RU-AidarNeural",
  "tgk": "tg-TJ-SharifNeural",
  "tir": "am-ET-AmehaNeural",
  "ton": "en-US-GuyNeural",
  "tsn": "en-US-GuyNeural",
  "tuk": "tk-TM-AmanNeural",
  "uig": "ug-CN-KashgarNeural",
  "vol": "en-US-GuyNeural",
  "wol": "en-US-GuyNeural",
  "xho": "xh-ZA-ThembaNeural",
  "ydd": "he-IL-AvriNeural",
  "aka": "en-US-GuyNeural",
  "bam": "fr-FR-HenriNeural",
  "bis": "en-US-GuyNeural",
  "bod": "zh-CN-YunxiNeural",
  "che": "ru-RU-DmitryNeural",
  "chv": "ru-RU-DmitryNeural",
  "dzo": "zh-CN-YunxiNeural",
  "ewe": "en-US-GuyNeural",
  "kab": "en-US-GuyNeural",
  "lug": "en-US-GuyNeural",
  "oss": "ru-RU-DmitryNeural",
  "ssw": "en-US-GuyNeural",
  "ven": "en-US-GuyNeural",
  "war": "en-US-GuyNeural",
  "nde": "en-US-GuyNeural",
  "nbl": "en-US-GuyNeural",
  "pam": "en-US-GuyNeural",
  "hil": "en-US-GuyNeural",
  "bcl": "en-US-GuyNeural",
  "min": "en-US-GuyNeural",
  "ace": "en-US-GuyNeural",
  "bug": "en-US-GuyNeural",
  "ban": "en-US-GuyNeural",
  "bjn": "en-US-GuyNeural",
  "mak": "en-US-GuyNeural",
  "sas": "en-US-GuyNeural",
  "tet": "en-US-GuyNeural",
  "cha": "en-US-GuyNeural",
  "niu": "en-US-GuyNeural",
  "tvl": "en-US-GuyNeural",
  "gil": "en-US-GuyNeural",
  "mah": "en-US-GuyNeural",
  "pau": "en-US-GuyNeural",
  "wls": "en-US-GuyNeural",
  "rar": "en-US-GuyNeural",
  "hif": "en-US-GuyNeural",
}

function isObject(value: unknown): value is Record<string, any> {
  return !!value && typeof value === "object" && !Array.isArray(value)
}

function isKnownEdgeTTSVoice(voice: string): boolean {
  return MIGRATION_V054_KNOWN_EDGE_TTS_VOICES.has(voice)
}

function createDefaultTTSLanguageVoices(): Record<string, string> {
  return {
    ...MIGRATION_V054_DEFAULT_LANGUAGE_VOICES,
  }
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value))
}

function toRateFromLegacySpeed(speed: unknown): number {
  if (typeof speed !== "number" || !Number.isFinite(speed)) {
    return 0
  }

  return clamp(Math.round((speed - 1) * 100), -100, 100)
}

function toClampedNumber(value: unknown): number | null {
  if (typeof value !== "number" || !Number.isFinite(value)) {
    return null
  }
  return clamp(Math.round(value), -100, 100)
}

function toEdgeVoice(voice: unknown): string {
  if (typeof voice === "string" && isKnownEdgeTTSVoice(voice)) {
    return voice
  }

  return MIGRATION_V054_FALLBACK_VOICE
}

export function migrate(oldConfig: any): any {
  if (!isObject(oldConfig)) {
    return oldConfig
  }

  const oldTts = isObject(oldConfig.tts) ? oldConfig.tts : {}
  const defaultVoice = toEdgeVoice(oldTts.voice)
  const languageVoices = createDefaultTTSLanguageVoices()
  languageVoices.eng = defaultVoice
  const migratedRate = toClampedNumber(oldTts.rate) ?? toRateFromLegacySpeed(oldTts.speed)
  const migratedPitch = toClampedNumber(oldTts.pitch) ?? 0
  const migratedVolume = toClampedNumber(oldTts.volume) ?? 0

  return {
    ...oldConfig,
    tts: {
      defaultVoice,
      languageVoices,
      rate: migratedRate,
      pitch: migratedPitch,
      volume: migratedVolume,
    },
  }
}
